edgeworthQuotes = [
    "Amateurs, amateurs. Listen to me, Mr. Wright. In the courtroom, evidence is everything. Without it, you have nothing. You ARE nothing",
    "I object! That was... objectionable!",
    "*Shaking* Upstart..! Amateur..! These accusations... are ludicrous!",
    "I was hoping to come up with a question while I was objecting, Your Honor... I didn't",
    "Indeed! Verily, I say... Ergo!",
    "[to Phoenix] Thanks to you, I am saddled with unnecessary... feelings.",
    "OBJECTION!",
    "(hits the desk) Yeah! Mr. Wright! Oops..!",
    "O-objection! I... object to the witness's talkativeness.",
    "So, you've come to laugh at the fallen attorney? Then laugh, laugh! Well? Why aren't you laughing?",
    "... You can wipe that foolish grin off your face now, Wright!",
    "What the hell was that wriggling piece of plywood!?",
    "This isn't the 'Phoenix Wright Wax Philosophical Power Hour'.",
    "When you've run into a wall with no place to go, return to the basics.",
    "Our job is to find truth, no matter how painful it may be.",
    "Y-your name, please!",
    "[to Phoenix] Thanks to you, I am saddled with unnecessary... feelings.",
    "Er... your name?",
    "Your Honor, this is ridiculous!",
    "The guilty will always lie, to avoid being found out.",
    "… Wright. Would you get a hold of yourself? You have it all wrong.",
    "…*sigh* Ironic that you of all people should say such a thing.",
    "That's not something I can answer for you… Wright… Only you can decide where to go from here.",
    "We aren't some sort of heroes. We're only human, you and I.",
    "The answer to that… is something you will find out on your own.",
    "After I left the Prosecutor's Office, I finally came to realize something.",
    "That's why you couldn't forgive me; this man who went into hiding. Isn't that right?",
    "This man who only had his sights set on 'victory', who ran away into the night…",
    "...Witness. Let's continue...",
    "Wright. I'll be sending the bill for the chewing gum to your office at a later date.",
    "OBJECTION! Wright. I thought years of school would have taught you how to construct a sentence.",
    "Subject, verb, object Wright. Did you skip basic grammar? The witness may continue.",
    "(Gumshoe indeed! Like gum on your shoe, he's impossible to get rid of!)",
    "That's what he'd do... That's the way Phoenix Wright would do this!",
    "Was it the evidence or the power of my glare that broke that lock...?",
    "His (Larry's) 'works of art' are a force of nature best measured on the Richter scale.",
    "Is this how it is for Wright? Is this what it's like to be a defense lawyer?",
    "...Nooooooooooooooooooooooooo!",
    "Thank god for inner monologue.",
    "This one single statement is so full of contradictions... For a moment there, I thought I was going to collapse.",
    "How long were you in the bath for, if you don't mind me asking?",
    "W-What are you going on about!? I was…(gets whipped) Gwah!",
    "Ah, that's right. I was in the middle of recreating a chess game.",
    "Excuse me, but may I have a word with you?",
    "I can't even begin to imagine what the plot of this movie would be like.",
    "It's just the food they serve in First Class.",
    "Detective Gumshoe! Am I going to have to charge you with invasion of privacy?!",
    "Why ask me to wake her when you can finally put that whip to an appropiate use?",
    "(Badger, badger, badger, badger ... Just what does she see in these silly things?",
    "Please stop stealing my lines!",
    "Your Honor, I'm sorry but... I cannot allow you to not allow me to make an objection!",
    "Hmm, a drink vending machine................ Ack!",
    "As a student of von Karma, I refuse to back down!",
    "*OBJECTION!* That statement contradicts this evidence!",
    "So that window on the other side belongs to the men's restroom...",
    "At your height? I'm not surprised.",
    "Nnghoooooooh! (I guess short people have feelings too!)",
    "I see you have no mercy for the elderly either",
    ".......What is wrong with these two women!? Why does my pain give them delight?",
    "Be careful about who you whip! Choose carefully, or we may be sued by....Nnghhoooh!",
    "Egad...! What a cold stare he's giving me!",
    "With your height, you'd need a step-ladder or four to accomplish that!",
    "I'll be the judge for that, Detective Gumshoe.",
    "How about we use this handkerchief to dry your little eyes?",
    "Nnnnghooooooh! My cravat! Don't blow your nose on that!",
    "Gnaaack! Wh-What are you hitting ME for!?",
    "When those which were split are made whole again... the truth will reveal itself.",
    "Because we are all in shock... and in awe of your utter stupidity.",
    "OBJECTION! Go away!",
    "I want you to answer this question honestly, and depending on your answer, I may let you live...",
    "H-How could this happen two days in a roooooooooooow!?",
    "Wait, hold on. Laaaaaaryyyy! It was you!? YOU'RE the one who wrote my Steel Samurai autograph!?",
    "[to Phoenix] Thanks to you, I am saddled with unnecessary... feelings.",
    "Sorry, but could you not speak to me now?",
    "Sorry, but could you not speak to me now?",
    ".................No.",
    "OBJECTION! I will never acknowledge you as the true Steel Samurai!",
    "O-Of course not, Detective!",
    "Ack! Hey! Detective Gumshoe! S-Stop that! I can't be seen doing... that!",
    "I have no real interest in the perceived worth of other people.",
    "As for my own worth, that is something only I can determine for myself.",
    "'Can I prove it...?' That isn't the issue. To simply 'prove it'. That's the only option!",
    "This is exactly why your salary keeps getting cut!",
    "It is a prosecutor's job to doubt people.",
    "… I see… Now I understand why you despise me so. However, you are mistaken.",
    "You are a defense lawyer. You can't run away from that. You can only fight. That's all you can do.",
    "Thanks to you, when you sealed off my path to a perfect win record… I began to realize the error of my ways.",
    "I realized that such things as a perfect win record were meaningless.",
    "You really should come with a supply of cheese to match your vintage whine.",
    "Be quiet and listen... Your Honor.",
    "Indeed! Verily, I say... Ergo!",
    "(slams desk) Name!",
    "All that I can hope to do is get every defendant declared 'guilty'! So I make that my policy.",
    "... You can wipe that foolish grin off your face now, Wright!",
    "Just remember one thing, Mr. Wright. Every time you point your finger, someone gets hurt.",
    "Very well, witness. Please describe the incident to us.",
    "Essentially... he would acquire unchecked authority over all investigations!",
    "...",
    "[to Phoenix] Thanks to you, I am saddled with unnecessary... feelings.",
]
